on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v2
      - run: pip install releng-tool
      - run: |
          bash --version
          nmake /?
          perl --version
          releng-tool --version
          sed --version
