on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
      - run: |
          (Get-Command bash).Path
          (Get-Command bash.exe).Path
          (Get-Command sh).Path
          (Get-Command sh.exe).Path
          (Get-Command perl).Path
          (Get-Command msys2).Path
      - uses: ilammy/msvc-dev-cmd@v1
      - run: bash -c pwd
      - run: bash.exe -c pwd
      - run: sh -c pwd
      - run: sh.exe -c pwd
      - run: |
          (Get-Command bash).Path
          (Get-Command bash.exe).Path
          (Get-Command sh).Path
          (Get-Command sh.exe).Path
          (Get-Command perl).Path
          (Get-Command msys2).Path
