on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      #- uses: msys2/setup-msys2@v2
      #  with:
      #    msystem: UCRT64
      #    update: true
      #    install: make
      - run: |
          (Get-Command bash).Path
          (Get-Command bash.exe).Path
          (Get-Command sh).Path
          (Get-Command sh.exe).Path
          (Get-Command make).Path
          (Get-Command perl).Path
      - uses: ilammy/msvc-dev-cmd@v1
      - run: 
        run: |
          bash -c pwd
          bash.exe -c pwd
          bash --version
          bash.exe --version
      - run: make --version
      - run: sh -c pwd
      - run: sh.exe -c pwd
      - shell: bash
        run: |
          bash --version
          which bash
          which sh
          which make
          which perl
      - name: Build release
        run: Remove-Item C:\Windows\System32\bash.exe
