on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: |
        bash .github/workflows/setup-waf.sh
        waf --help
