on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - run: pip install releng-tool
      - run: |
          bash --version
          nmake /?
          perl --version
          releng-tool --version
          sed --version
