on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install releng-tool
      - run: |
          bash --version
          nmake /?
          perl --version
          releng-tool --version
          sed --version
