on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: make
      - run: |
          (Get-Command bash).Path
          (Get-Command bash.exe).Path
          (Get-Command sh).Path
          (Get-Command sh.exe).Path
          (Get-Command make).Path
          (Get-Command perl).Path
      #    (Get-Command msys2).Path
      - uses: ilammy/msvc-dev-cmd@v1
      - run: pip install releng-tool
      - run: bash -c pwd
      - run: bash.exe -c pwd
      - run: make --version
      - run: sh -c pwd
      - run: sh.exe -c pwd
      - run: sh.exe -c pwd
      - shell: bash
        run: |
          which bash
          which sh
          which make
          which perl
          releng-tool --version
