on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
      - run: |
          (Get-Command bash).Path
          (Get-Command sh).Path
          (Get-Command perl).Path
          (Get-Command msys2).Path
      - uses: ilammy/msvc-dev-cmd@v1
      - run: pip install releng-tool
      - run: |
          bash --version
          echo ""
          # nmake /?
          # echo ""
          hg --version
          echo ""
          perl --version
          echo ""
          releng-tool --version
          echo ""
          sed --version
          echo ""
          uname -a
      - run: env
      - run: bash -c "echo 123"
      - run: msys2 -c 'uname -a'
      - run: |
          (Get-Command bash).Path
          (Get-Command sh).Path
          (Get-Command perl).Path
          (Get-Command msys2).Path
